exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

title : CSVY yaml frontmatter for csv file format
tagline: datasets,csv,yml,
author :
  name : CSVY's Team
  email : blah@email.test
  github : csvy
  twitter : jrovegno
