exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

title : CSVY yaml frontmatter for csv file format
tagline: datasets,csv,yml,
author :
  name : Name Lastname
  email : blah@email.test
  github : jrovegno
  twitter : jrovegno
